package Corba;


/**
* Corba/JoueurActionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public abstract class JoueurActionPOA extends org.omg.PortableServer.Servant
 implements Corba.JoueurActionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creerCompte", new java.lang.Integer (0));
    _methods.put ("authentifier", new java.lang.Integer (1));
    _methods.put ("deconnecter", new java.lang.Integer (2));
    _methods.put ("donnerScore", new java.lang.Integer (3));
    _methods.put ("donnerListeConnectes", new java.lang.Integer (4));
    _methods.put ("donnerClassement", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Corba/JoueurAction/creerCompte
       {
         String identifiant = in.read_string ();
         String motDePasse = in.read_string ();
         String $result = null;
         $result = this.creerCompte (identifiant, motDePasse);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Corba/JoueurAction/authentifier
       {
         String identifiant = in.read_string ();
         String motDePasse = in.read_string ();
         String $result = null;
         $result = this.authentifier (identifiant, motDePasse);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Corba/JoueurAction/deconnecter
       {
         String identifiant = in.read_string ();
         String $result = null;
         $result = this.deconnecter (identifiant);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Corba/JoueurAction/donnerScore
       {
         String identifiant = in.read_string ();
         int $result = (int)0;
         $result = this.donnerScore (identifiant);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // Corba/JoueurAction/donnerListeConnectes
       {
         String identifiant = in.read_string ();
         Corba.Joueur $result[] = null;
         $result = this.donnerListeConnectes (identifiant);
         out = $rh.createReply();
         Corba.JoueursHelper.write (out, $result);
         break;
       }

       case 5:  // Corba/JoueurAction/donnerClassement
       {
         String identifiant = in.read_string ();
         Corba.Joueur $result[] = null;
         $result = this.donnerClassement (identifiant);
         out = $rh.createReply();
         Corba.JoueursHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Corba/JoueurAction:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public JoueurAction _this() 
  {
    return JoueurActionHelper.narrow(
    super._this_object());
  }

  public JoueurAction _this(org.omg.CORBA.ORB orb) 
  {
    return JoueurActionHelper.narrow(
    super._this_object(orb));
  }


} // class JoueurActionPOA
