package Corba;


/**
* Corba/JoueurAction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public interface JoueurAction extends JoueurActionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface JoueurAction
