package Corba;


/**
* Corba/Joueur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public final class Joueur implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public String motDePasse = null;
  public String identifiant = null;

  public Joueur ()
  {
  } // ctor

  public Joueur (String _nom, String _motDePasse, String _identifiant)
  {
    nom = _nom;
    motDePasse = _motDePasse;
    identifiant = _identifiant;
  } // ctor

} // class Joueur
