package Corba;

/**
* Corba/JoueurActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public final class JoueurActionHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.JoueurAction value = null;

  public JoueurActionHolder ()
  {
  }

  public JoueurActionHolder (Corba.JoueurAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.JoueurActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.JoueurActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.JoueurActionHelper.type ();
  }

}
