package Corba;

/**
* Corba/PartieActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public final class PartieActionHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.PartieAction value = null;

  public PartieActionHolder ()
  {
  }

  public PartieActionHolder (Corba.PartieAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.PartieActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.PartieActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.PartieActionHelper.type ();
  }

}
