package Corba;

/**
* Corba/PartieHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public final class PartieHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.Partie value = null;

  public PartieHolder ()
  {
  }

  public PartieHolder (Corba.Partie initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.PartieHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.PartieHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.PartieHelper.type ();
  }

}
