package Corba;


/**
* Corba/PartieListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 35 CEST
*/

public final class PartieListHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.Partie value[] = null;

  public PartieListHolder ()
  {
  }

  public PartieListHolder (Corba.Partie[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.PartieListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.PartieListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.PartieListHelper.type ();
  }

}
