package tier2_Corba;


/**
* tier2_Corba/PartieActionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public abstract class PartieActionPOA extends org.omg.PortableServer.Servant
 implements tier2_Corba.PartieActionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPartie", new java.lang.Integer (0));
    _methods.put ("connectToPartie", new java.lang.Integer (1));
    _methods.put ("disconnectToPartie", new java.lang.Integer (2));
    _methods.put ("getScoreJoueur", new java.lang.Integer (3));
    _methods.put ("getPartiesEnAttente", new java.lang.Integer (4));
    _methods.put ("getPartiesEnCours", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tier2_Corba/PartieAction/createPartie
       {
         tier2_Corba.Joueur J = tier2_Corba.JoueurHelper.read (in);
         tier2_Corba.PartieHolder p = new tier2_Corba.PartieHolder ();
         int $result = (int)0;
         $result = this.createPartie (J, p);
         out = $rh.createReply();
         out.write_long ($result);
         tier2_Corba.PartieHelper.write (out, p.value);
         break;
       }

       case 1:  // tier2_Corba/PartieAction/connectToPartie
       {
         tier2_Corba.Joueur J = tier2_Corba.JoueurHelper.read (in);
         tier2_Corba.Partie p = tier2_Corba.PartieHelper.read (in);
         String $result = null;
         $result = this.connectToPartie (J, p);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // tier2_Corba/PartieAction/disconnectToPartie
       {
         tier2_Corba.Joueur J = tier2_Corba.JoueurHelper.read (in);
         tier2_Corba.Partie P = tier2_Corba.PartieHelper.read (in);
         String $result = null;
         $result = this.disconnectToPartie (J, P);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // tier2_Corba/PartieAction/getScoreJoueur
       {
         tier2_Corba.Joueur J = tier2_Corba.JoueurHelper.read (in);
         int $result = (int)0;
         $result = this.getScoreJoueur (J);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // tier2_Corba/PartieAction/getPartiesEnAttente
       {
         tier2_Corba.Partie $result[] = null;
         $result = this.getPartiesEnAttente ();
         out = $rh.createReply();
         tier2_Corba.PartieListHelper.write (out, $result);
         break;
       }

       case 5:  // tier2_Corba/PartieAction/getPartiesEnCours
       {
         tier2_Corba.Partie $result[] = null;
         $result = this.getPartiesEnCours ();
         out = $rh.createReply();
         tier2_Corba.PartieListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tier2_Corba/PartieAction:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PartieAction _this() 
  {
    return PartieActionHelper.narrow(
    super._this_object());
  }

  public PartieAction _this(org.omg.CORBA.ORB orb) 
  {
    return PartieActionHelper.narrow(
    super._this_object(orb));
  }


} // class PartieActionPOA
