package tier2_Corba;


/**
* tier2_Corba/Partie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public final class Partie implements org.omg.CORBA.portable.IDLEntity
{
  public int idPartie = (int)0;
  public String nomPartie = null;
  public int nbrJoueurPartie = (int)0;

  public Partie ()
  {
  } // ctor

  public Partie (int _idPartie, String _nomPartie, int _nbrJoueurPartie)
  {
    idPartie = _idPartie;
    nomPartie = _nomPartie;
    nbrJoueurPartie = _nbrJoueurPartie;
  } // ctor

} // class Partie
