package Corba;


/**
* Corba/JoueurActionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 14 CEST
*/

public interface JoueurActionOperations 
{
  String creerCompte (String identifiant, String motDePasse);
  String authentifier (String identifiant, String motDePasse);
  String deconnecter (String identifiant);
  int donnerScore (String identifiant);
  Corba.Joueur[] donnerListeConnectes (String identifiant);
  Corba.Joueur[] donnerClassement (String identifiant);
} // interface JoueurActionOperations
