package Corba;


/**
* Corba/JoueurActionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 14 CEST
*/

abstract public class JoueurActionHelper
{
  private static String  _id = "IDL:Corba/JoueurAction:1.0";

  public static void insert (org.omg.CORBA.Any a, Corba.JoueurAction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Corba.JoueurAction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Corba.JoueurActionHelper.id (), "JoueurAction");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Corba.JoueurAction read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_JoueurActionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Corba.JoueurAction value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Corba.JoueurAction narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Corba.JoueurAction)
      return (Corba.JoueurAction)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Corba._JoueurActionStub stub = new Corba._JoueurActionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Corba.JoueurAction unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Corba.JoueurAction)
      return (Corba.JoueurAction)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Corba._JoueurActionStub stub = new Corba._JoueurActionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
