package Corba;


/**
* Corba/PartiesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 13 juin 2016 22 h 14 CEST
*/

public final class PartiesHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.Partie value[] = null;

  public PartiesHolder ()
  {
  }

  public PartiesHolder (Corba.Partie[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.PartiesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.PartiesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.PartiesHelper.type ();
  }

}
