package tier2_Corba;


/**
* tier2_Corba/_PartieActionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public class _PartieActionStub extends org.omg.CORBA.portable.ObjectImpl implements tier2_Corba.PartieAction
{

  public int createPartie (tier2_Corba.Joueur J, tier2_Corba.PartieHolder p)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPartie", true);
                tier2_Corba.JoueurHelper.write ($out, J);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                p.value = tier2_Corba.PartieHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createPartie (J, p        );
            } finally {
                _releaseReply ($in);
            }
  } // createPartie

  public String connectToPartie (tier2_Corba.Joueur J, tier2_Corba.Partie p)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("connectToPartie", true);
                tier2_Corba.JoueurHelper.write ($out, J);
                tier2_Corba.PartieHelper.write ($out, p);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connectToPartie (J, p        );
            } finally {
                _releaseReply ($in);
            }
  } // connectToPartie

  public String disconnectToPartie (tier2_Corba.Joueur J, tier2_Corba.Partie P)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("disconnectToPartie", true);
                tier2_Corba.JoueurHelper.write ($out, J);
                tier2_Corba.PartieHelper.write ($out, P);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return disconnectToPartie (J, P        );
            } finally {
                _releaseReply ($in);
            }
  } // disconnectToPartie

  public int getScoreJoueur (tier2_Corba.Joueur J)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getScoreJoueur", true);
                tier2_Corba.JoueurHelper.write ($out, J);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getScoreJoueur (J        );
            } finally {
                _releaseReply ($in);
            }
  } // getScoreJoueur

  public tier2_Corba.Partie[] getPartiesEnAttente ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPartiesEnAttente", true);
                $in = _invoke ($out);
                tier2_Corba.Partie $result[] = tier2_Corba.PartieListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPartiesEnAttente (        );
            } finally {
                _releaseReply ($in);
            }
  } // getPartiesEnAttente

  public tier2_Corba.Partie[] getPartiesEnCours ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPartiesEnCours", true);
                $in = _invoke ($out);
                tier2_Corba.Partie $result[] = tier2_Corba.PartieListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPartiesEnCours (        );
            } finally {
                _releaseReply ($in);
            }
  } // getPartiesEnCours

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tier2_Corba/PartieAction:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PartieActionStub
