package tier2_Corba;


/**
* tier2_Corba/JoueurActionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public abstract class JoueurActionPOA extends org.omg.PortableServer.Servant
 implements tier2_Corba.JoueurActionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createJoueur", new java.lang.Integer (0));
    _methods.put ("connectJoueur", new java.lang.Integer (1));
    _methods.put ("disconectJoueur", new java.lang.Integer (2));
    _methods.put ("getScoreJoueur", new java.lang.Integer (3));
    _methods.put ("getJoueursConnect", new java.lang.Integer (4));
    _methods.put ("getJoueursOrder", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tier2_Corba/JoueurAction/createJoueur
       {
         String login = in.read_string ();
         String pass = in.read_string ();
         String $result = null;
         $result = this.createJoueur (login, pass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // tier2_Corba/JoueurAction/connectJoueur
       {
         String login = in.read_string ();
         String pass = in.read_string ();
         String $result = null;
         $result = this.connectJoueur (login, pass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // tier2_Corba/JoueurAction/disconectJoueur
       {
         String login = in.read_string ();
         String $result = null;
         $result = this.disconectJoueur (login);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // tier2_Corba/JoueurAction/getScoreJoueur
       {
         String login = in.read_string ();
         int $result = (int)0;
         $result = this.getScoreJoueur (login);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // tier2_Corba/JoueurAction/getJoueursConnect
       {
         tier2_Corba.Joueur $result[] = null;
         $result = this.getJoueursConnect ();
         out = $rh.createReply();
         tier2_Corba.JoueurListHelper.write (out, $result);
         break;
       }

       case 5:  // tier2_Corba/JoueurAction/getJoueursOrder
       {
         tier2_Corba.Joueur $result[] = null;
         $result = this.getJoueursOrder ();
         out = $rh.createReply();
         tier2_Corba.JoueurListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tier2_Corba/JoueurAction:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public JoueurAction _this() 
  {
    return JoueurActionHelper.narrow(
    super._this_object());
  }

  public JoueurAction _this(org.omg.CORBA.ORB orb) 
  {
    return JoueurActionHelper.narrow(
    super._this_object(orb));
  }


} // class JoueurActionPOA
