package tier2_Corba;


/**
* tier2_Corba/Joueur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public final class Joueur implements org.omg.CORBA.portable.IDLEntity
{
  public String login = null;
  public String pass = null;
  public int score = (int)0;

  public Joueur ()
  {
  } // ctor

  public Joueur (String _login, String _pass, int _score)
  {
    login = _login;
    pass = _pass;
    score = _score;
  } // ctor

} // class Joueur
