package tier2_Corba;


/**
* tier2_Corba/JoueurListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public final class JoueurListHolder implements org.omg.CORBA.portable.Streamable
{
  public tier2_Corba.Joueur value[] = null;

  public JoueurListHolder ()
  {
  }

  public JoueurListHolder (tier2_Corba.Joueur[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tier2_Corba.JoueurListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tier2_Corba.JoueurListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tier2_Corba.JoueurListHelper.type ();
  }

}
