package tier2_Corba;


/**
* tier2_Corba/PartieActionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tier2.idl
* dimanche 12 juin 2016 00 h 02 CEST
*/

public interface PartieActionOperations 
{
  int createPartie (tier2_Corba.Joueur J, tier2_Corba.PartieHolder p);
  String connectToPartie (tier2_Corba.Joueur J, tier2_Corba.Partie p);
  String disconnectToPartie (tier2_Corba.Joueur J, tier2_Corba.Partie P);
  int getScoreJoueur (tier2_Corba.Joueur J);
  tier2_Corba.Partie[] getPartiesEnAttente ();
  tier2_Corba.Partie[] getPartiesEnCours ();
} // interface PartieActionOperations
